### ISSUE TITLE
Could the extension be tagged?

### ISSUE THREAD

**Issue by CsarRamos** [ginkgostreet/com.ginkgostreet.mosaicotoolbarconfig#2]
Hello, could the extension be tagged? it would make it easier to track and handle the versions this way. Thank you!

**Comment by caracolmzd** [comment]
Hello,
Are you just asking for a tag, or are you asking for this to be published in the extension directory?

@fulltrucker , was this every published in the directory? I'm not finding it.

**Comment by CsarRamos** [comment]
> Hello,
> Are you just asking for a tag, or are you asking for this to be published in the extension directory?
> 
> @fulltrucker , was this every published in the directory? I'm not finding it.

Hello, just asking for a tag

**Comment by fulltrucker** [comment]
> @fulltrucker , was this every published in the directory? I'm not finding it.

I don't think it was ever published, might not have even been submitted. The README says: "This extension has not yet been published for in-app installation."

**Comment by caracolmzd** [comment]
Tagged.
Are you the César that is working on https://civicrm.org/extensions/mosaico-extras ?

There are no current plans for this extension, so if you want to incorporate the code into another extension, it would probably be a benefit.

Cheers

**Comment by CsarRamos** [comment]
> Tagged.
> Are you the César that is working on https://civicrm.org/extensions/mosaico-extras ?
> 
> There are no current plans for this extension, so if you want to incorporate the code into another extension, it would probably be a benefit.
> 
> Cheers

Good to know, thanks!  I am working on it and with your permission I will include the code in a future version. Cheers!

**Comment by caracolmzd** [comment]
Cool, let us know when you have a release that incorporates this functionality and we will add a link to the README.

**Comment by CsarRamos** [comment]
> Cool, let us know when you have a release that incorporates this functionality and we will add a link to the README.

Hello, the extension is already published in the CiviCRM directory, I have adjusted the development to work with the new version of Mosaico. https://lab.civicrm.org/extensions/mosaicoextras/-/blob/1.0.0-beta/README.md 
If you have any suggestions, please let me know, Thanks!

**Comment by caracolmzd** [comment]
Thanks César!
I've put a notice and link to your extension in the README.

Cheers
